### ISSUE TITLE
Fire observer only once when element enters the viewport

### ISSUE THREAD

**Issue by sethzindler** [megurock/vue-intersect-directive#1]
Hi there,

I'm liking this simple project of yours, however, I'm having a bit of trouble making the observer fire only once, as opposed to each time the element enters the viewport. In other components and plugins I have found, there is a "once" option via the IO API, but I can't seem to get that working here.

Any ideas are appreciated.

**Comment by megurock** [comment]
Hi @sethzindler .

Having a way of stopping observer is a nice idea. 😄 
I have added `disposeWhen` property, instead of `once` property, because this Plugin accepts both `true` and `false` props at the same time.

https://github.com/megurock/vue-intersect-directive/tree/auto-dispose#stop-observing

Do you think this will help you?

**Comment by sethzindler** [comment]
Looks like that worked! Please let me know when you have committed to the master branch so I can update the package in my project.

Thanks again for that feature!

**Comment by megurock** [comment]
I have merged the new feature to the master branch, and also published to the [NPM](https://www.npmjs.com/package/vue-intersect-directive) as version 1.1.0.
Thank you for using my code. 😎
